---
# cloud-config

# final_message
# default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds
# this message is written by cloud-final when the system is finished
# its first boot
final_message: "The system is finally up, after $UPTIME seconds"

# SEE: https://github.com/number5/cloud-init/blob/main/doc/examples/cloud-config-apt.txt
apt:
  sources:
    envoy:
      source: "deb [arch=amd64] https://deb.dl.getenvoy.io/public/deb/ubuntu impish main"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v2

        mQGNBGB3BbgBDAC/UUHAjsA6eo9TCnMu1Owl4griISUjAqXPw0WRVBaeFnXf6Dzb
        /o8/oekohX1mJ4MCDKydp+VDTsWMcqdRM2NVyO5ZfK3dF+HITm3UJVwaJAXxmigM
        eE2lbNTtvYEQVHcoNS/8NtWdAmXt0Oy9sGlzy7Ehqpj0xSboWE7xkDicTY7e4fJe
        zFZd0B8juEWfo0gYkrZ9O8cWFPR68nCroedR3Zmira/1CqmNJyCSZZs9KK+aPJDG
        FhsWM1pJKEBVhWZ1ALqBEz4LpynTX6/s9tcVgTkYrpgmaUxKL9De/ZapyKUIMwmz
        wAQjtQxCbKpI9XOnzjjmBNinEVJJAcKj/SdhZTYoMAzxN+uePxEoLyyJBVjjNWng
        1/cYYr3wo9veNU3j0f8lhim6j2J9d8Pvpy+2wXpj7Kyvsp11U8lbyIZYeTTYz3rR
        ZOK+nkfDuPv4Jghk4Q92hSZnkkbLAt1qM6YuLkcsMwGYm7oiIr0qSaD7H1uhx7yl
        OWe+oLyG7hkDvA0AEQEAAbRBQ2xvdWRzbWl0aCBQYWNrYWdlICh0ZXRyYXRlL2dl
        dGVudm95LWRlYikgPHN1cHBvcnRAY2xvdWRzbWl0aC5pbz6JAbcEEwEIACEFAmB3
        BbgCGy8FCwkIBwMFFQoJCAsFFgIDAQACHgECF4AACgkQgRW6jmKcwHRTZwwAr5Ft
        v+8gzwWFsvYcKassTUu3tiq9cwya3TtcGT/JDuf3P2u+bn6eeqqsENaOzsgUqXds
        GohQey3XMlVrHnQENOQwBtF2QLAlWBmkNGN//50Z0yAvXnlAbgw+B3hJI8f/3Q6U
        TSbISxGqAhvCkluht9Tufn5KTVdB4chBjeUuuipjeOX575SHJ+A+W+ht23Pkbdei
        ssY5RRG5+7rFc3rzBLOpJV6XLnBfoOMJGJv3x4Psslw7EAy4UEQW/WU7xV1pEj8X
        MwWX5pHb/tZZDWAcZwno7yGK6FDaSVFtNNlIQ1mBXpdoCgzWSgvmsMRjf8AY3Amz
        3VR0nSXqduEFfdcaqniUXwqDF0dX12/kJtgjzOgkKyYTGo/n/VY4zC7jXzajUEky
        /lOzhwyLeibkKm88HsJdbMf3Fo+2BYLGL0VYHTANXyguDionYePa2nPqqEP5U5/t
        huAQ/FuGXuMe7rHjXspvZ8tJdbKXCsHB+deZC0E3nwHZZAB3jjZKGjY8a67P
        =ldE4
        -----END PGP PUBLIC KEY BLOCK-----
    hashicorp:
      source: "deb [arch=amd64] https://apt.releases.hashicorp.com impish main"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBF60TuYBEADLS1MP7XrMlRkn1Y54cb2UclUMH8HkIRfBrhk5Leo9kNZc/2QD
        LmdQbi3UbZkz0uVkHqbFDgV5lAnukCnxgr9BqnL0GJpO78le7gCCbM5bR4rTJ6Ar
        OOtIKf25smGTIpbSwNdj8BOLqiExGFj/9L5X9S5kfq3vtuYt+lmxKkIrEPjSYnFR
        TQ2mTL8RM932GJod/5VJ2+6YvrCjtPu5/rW02H1U2ZHiTtX6ZGnIvv/sprKyFRqT
        x4Ib+o9XwXof/LuxTMpVwIHSzCYanH5hPc7yRGKzIntBS+dDom+h9smx7FTgpHwt
        QRFGLtVoHXqON6nXTLFDkEzxr+fXq/bgB1Kc1TuzvoK601ztQGhhDaEPloKqNWM8
        Ho7JU1RpnoWr5jOFTYiPM9uyCtFNsJmD9mt4K8sQQN7T2inR5Us0o510FqePRFeX
        wOJUMi1CbeYqVHfKQ5cWYujcK8pv3l1a6dSBmFfcdxtwIoA16JzCrgsCeumTDvKu
        hOiTctb28srL/9WwlijUzZy6R2BGBbhP937f2NbMS/rpby7M1WizKeo2tkKVyK+w
        SUWSw6EtFJi7kRSkH7rvy/ysU9I2ma88TyvyOgIz1NRRXYsW7+brgwXnuJraOLaB
        5aiuhlngKpTPvP9CFib7AW2QOXustMZ7pOUREmxgS4kqxo74CuFws163TwARAQAB
        tFFIYXNoaUNvcnAgU2VjdXJpdHkgKEhhc2hpQ29ycCBQYWNrYWdlIFNpZ25pbmcp
        IDxzZWN1cml0eStwYWNrYWdpbmdAaGFzaGljb3JwLmNvbT6JAk4EEwEIADgWIQTo
        oDLglNjrTqGJ0nDaQYyIoyGfewUCXrRO5gIbAwULCQgHAgYVCgkICwIEFgIDAQIe
        AQIXgAAKCRDaQYyIoyGfe6/WD/9dTM/1OSgbvSPpPJOOcn5L1nOKRBJpztr4V0ky
        GoCDakIQ/sykbcuHXP79FGLzrM8zQOsbvVp/Z2lsWBnxkT8KWM+8LZxYToRGdZhr
        huFPHV9df0vAsZGisu4ejHDneHOTO3KqVotkky34jUSjBL7Q8uwXHY9r+5hb452N
        vafN1w0Y1QVhb6JjjwWHR8Rf9qkSIEi6m9o8a1M54yQC2y/Zrs6+4F3zZ4uYfTvz
        MyFfj0P5VmAoaowLSRdb2/JTObu0+zpKN+PjZA8BcnOf/pvqmEz83FIfo6zJLScx
        TVaAwj5Iz/jS04x7EvBuIP3vpgv1R6r+t0qU/7hpu7Oc0dsxhL+C8BpVY26/2hvX
        ozN5eG0ysSwexqwls+bnRgd6KdoHlWFNfbW8RCPKyb/s+tmFqGAY/QmxMkukgnXQ
        WvBoa0Gdv2AFVLYup9tEO1zF4zBPh5oQwAXDNudLTHJ4KmyEwWsOQJUjNB4y4a7j
        iGgK77T4KKXpo7pVDP8Ur+tmNH/d+/YFjxrfJvWt4ypE5dZmFO/FrUMvIGglOLDt
        A+SiQe73IpEebB8PiqNlqJ2NU7artuRxYQVColt+/1puIHwV+h0SnMoUEvYqAtxP
        J/N3JaiytWlesPPFWvhU/JGUAld5coEU2gbYtlenV/YmdjilIBu50sMSPGF5/6gv
        BAA/DbkCDQRetE7mARAA0OH1pn0vdEfSm1kdqIDP3BXBD0BRHNNgGpyXXRRJFaip
        bmpu7jSv3FsvN/NmG3BcLXXLFvwY/eIOr6fxRye+a5FSQEtvBnI1GHNmD5GAVT/H
        KiwrT5e3ReR/FQS7hCXWU4OA2bKmSEdkJ952NhyYeyAKbkOBgbnlEhtWOAdMI7ws
        peHAlHDqfGVOKXDh+FddCUQj/yZ2rblSzFdcC9gtcJSyHWgOQdVAEesEZ16hcZoj
        +6O+6BXOQWOo7EPD7lA9a1qesBkSRcxQn48IVVZ2Qx2P2FtCfF+SFX+HQdqJGl15
        qxE5CXTuJCMmCVnWhvcLW405uF/HmMFXdqGobEDiQsFFQrfpPVOi4T90VkW8P81s
        uPoAlWht1CppNnmhWlvPQsPK/oSMBBOvOEH1EnWJate8yIkveNbqzrE7Xt3sjF6k
        yqXaF+qW8OcDvSH/fgvVd21G10Cm77Z2WaKWvfi221oWj+WrgT8cCYv0AVmaLRMe
        dajuYlPRQ8KaZaESza2eXggOMP5LQs/mQgfHfwSRekSbKg/L6ctp+xrZ0DPj4iIl
        8+H4DxTILopAFWXA1a+uMVp8mV77gA9PyV3nIkrwgaZQ8MdhoKwvN/+SbvhpdzyF
        UekzMP/HOaC6JgAomluwnFCdMDFa3FMCF3QUcIyY556QdoFD7g6033xqV6vL+d8A
        EQEAAYkCNgQYAQgAIBYhBOigMuCU2OtOoYnScNpBjIijIZ97BQJetE7mAhsMAAoJ
        ENpBjIijIZ97lecP+wTgSqhCz3TlUshR8lVrzECueIg3jh3+lY56am9X4MoZ2DAW
        IXKjWKVWO55WPYD15A7+TbDyb4zh55m81LxSpV0CSRN4aPuixosWP4d0l+363D2F
        oudz+QyvoK5J2sKFPMfhdTgGsEYVO/Zbhus5oNi0kjUTD9U7jHWPS3ilvk/g2F+k
        T68lL9+oooleeT+kcBvbKt487JUOwMrkmHqNZdh8qmvMASAuqBcEcqjz96kVEMJY
        bhn2skexKfIncoo/btixzJUbnplpDfibFxUHhvWWdwIv4kl3YnrCKKGSDoJcG1mV
        sQegK4jWVGrqY8MnCI48iotP18ZxyqOycsZvs2jNmFlKwD9s1mrlr97HZ1MYbLWr
        Hq06owH0AzVRM7tzMK7EuHkFLcoa8qh3oijn8O0B7xNOKpTZ2DjajQ/1w8nqmMi5
        Z3Wie6ivKng/7p6c6HDrKjoQYc0/fuh1YnL60JG2Arn1OwdBsLDlzPL+Ro5iNwoJ
        hZ+stxoZT48iAIWonBsLU11Y+MSwWdN1Eh411HTTunrEs6SafMEhnPi7vvUIZhny
        Es0qOM/IUR1I0VtsurSn8aA6Y2Bp73+HuqFLx13/tPKBIUo6D7n/ywUlDCo7wtCw
        aSgXPw6uF+0CyLOQ0haf2j6w1OB8ayEGSkTPER5rImCJf3MGw8IECGrErAd+
        =emKC
        -----END PGP PUBLIC KEY BLOCK-----

# Update apt database on first boot (run 'apt-get update').
# Note, if packages are given, or package_upgrade is true, then
# update will be done independent of this setting.
#
# Default: false
# Aliases: apt_update
package_update: true

# Install additional packages on first boot
#
# Default: none
#
# if packages are specified, this apt_update will be set to true
#
# packages may be supplied as a single package name or as a list
# with the format [<package>, <version>] wherein the specifc
# package version will be installed.
packages:
  - nomad
  - consul
  - docker.io
  - getenvoy-envoy

runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, enable, docker.service]
  - [systemctl, start, --no-block, docker.service]
  - [systemctl, enable, consul.service]
  - [systemctl, start, --no-block, consul.service]
  - [systemctl, enable, nomad.service]
  - [systemctl, start, --no-block, nomad.service]

# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
#
# Note: Content strings here are truncated for example purposes.
write_files:
- content: |
    # Nomad dev mode configuration
    server {
      enabled          = true
      bootstrap_expect = 1
    }

    client {
      enabled       = true
    }

    plugin "raw_exec" {
      config {
        enabled = true
      }
    }
  path: /etc/nomad/01-devmode.hcl
- content: |
    # Consul dev mode configuration
    datacenter = "consul-dc-dev"
    server = true
    bootstrap_expect = 1
    ui_config {
      enabled = true
    }
    connect {
      enabled = true
    }
    bind_addr = "0.0.0.0" # Listen on all IPv4
    ports {
      "grpc" = 8502
    }
  path: /etc/consul.d/01-devmode.hcl
